#program file
from LiFunctions import *
turtle.bgcolor("black")

bob.color("gold")
bob.begin_fill()
bob.circle(100)
bob.fillcolor("gold")
bob.end_fill()

jump(-45,100)
bob.color("saddlebrown")
bob.begin_fill()
bob.circle(15)
bob.end_fill()

jump(45,100)
bob.color("saddlebrown")
bob.begin_fill()
bob.circle(15)
bob.end_fill()

jump(-45,50)
bob.width(8)
bob.color("saddlebrown")
bob.begin_fill()
bob.fd(90)
bob.end_fill()

bob.color("white")
bob.begin_fill()
bob.width(2)
bob.right(120)
bob.fd(15)
bob.right(120)
bob.fd(15)
bob.right(120)
bob.fd(15)
bob.end_fill()

jump(-45,50)
bob.color("white")
bob.begin_fill()
bob.width(2)
bob.left(180)
bob.left(120)
bob.fd(15)
bob.left(120)
bob.fd(15)
bob.left(120)
bob.fd(15)
bob.end_fill()

jump(10000,1000)
